chore(package): add babel-jest
```
TypeError: babelJest.createTransformer is not a function
    at Object.<anonymous> (/home/runner/work/web/web/node_modules/react-app-rewired/scripts/utils/babelTransform.js:16:28)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at requireOrImportModule (/home/runner/work/web/web/node_modules/jest-util/build/requireOrImportModule.js:53:28)
    at /home/runner/work/web/web/node_modules/@jest/transform/build/ScriptTransformer.js:382:73
    at Array.map (<anonymous>)
```