test: resolve Router conflict in test setup
This gets the CI passing and resolves the following error:

    TypeError: reactAct is not a function

      4 |
      5 | test('renders 2anki.net about', () => {
    > 6 |   render(<App />);
        |         ^
      7 |   const linkElement = screen.getByText(/What is 2anki/i);
      8 |   expect(linkElement).toBeInTheDocument();
      9 | });

t# Please enter the commit message for your changes. Lines starting